#!/bin/env python3

from werkzeug.security import generate_password_hash
import getpass
import tbsnippets


# This function takes the user's unique numeric ID, generated by the database and the paswword input by the administrator
# to create a credential management record for the new user. The record also prefills the mandatory boolean fields used for
# tracking whether an account is locked or disabled. 
# The password is displayed to the screen to allow the administrator to confirm their typing. This could also be addressed
# with a confirmation step in the inital password input section if there are concerns with shoulder surfing.
#
def newuserauthnz(pwd,shpwd,uid):
    print("This is the current password: {}".format(pwd))

    #print("This is the pbkdf2 hash value: {}".format(shpwd[20:]))
    # create generation SQL
    regdate=tbsnippets.getcurdate()
    newusercred = ''' INSERT into userauthnz(userid,userpasswd,userlocked,forcepwdchange,activestatus,userregistration) \
        VALUES(%s,%s,%s,%s,%s,%s)'''
    valuestuple=(int(uid),shpwd,0,0,1,regdate)
    print(valuestuple)
    try:
            thisdbh=tbsnippets.sbxdbconnect('10.100.200.3','sbxuser','someP@SSwerd','tbsbx')
            thiscur=thisdbh.cursor()
            result=thiscur.execute(newusercred, valuestuple)
            thisdbh.commit()
            thisdbh.close()
            return result
    except Exception as err:
            print(err)
            return None


def createdatauser(ufn,usn,udn,aid,ua):
    newusersql= ''' INSERT into datauser(userforename,usersurname,userdisplayname,useraccessid,useragency) VALUES (%s,%s,%s,%s,%s) '''
    valuestuple= (ufn,usn,udn,aid,ua) 
    try:
            thisdbh=tbsnippets.sbxdbconnect('10.100.200.3','sbxuser','someP@SSwerd','tbsbx')
            thiscur=thisdbh.cursor()
            result=thiscur.execute(newusersql, valuestuple)
            thisdbh.commit()
            thisdbh.close()
            return result
    except Exception as err:
            print(err)
            return None

def getuserid(accessid):
    uidsql = "SELECT userid,useraccessid from datauser WHERE useraccessid='{}'".format(accessid)
    try:
        thisdbh=tbsnippets.sbxdbconnect('10.100.200.3','sbxuser','someP@SSwerd','tbsbx')
        thiscur=thisdbh.cursor()
        result=thiscur.execute(uidsql)
        # get file meta data needed for download and the file data stored as bytes in the database
        recordstuple = thiscur.fetchone()
        uid=recordstuple[0]  
        aid=recordstuple[1]
        thisdbh.close()
        return uid
    except Exception as err:
            print(err)
            return None

def checkgenpasswd(pwd):
    if len(pwd) < 10:
        print('password is too short, please re-enter')
        return None
    else:
        shpwd=generate_password_hash(pwd, method='pbkdf2:sha256',salt_length=16)
        return shpwd        


def main():
    quit=False
    while(not quit):
        #  Do all the intial user information collection
        print("Creating new user account for SFR")
        print("-----------------------------------\n")
        print("Collecting User information first:")
        userforename=input("User's legal forename (first, formal)?: ")
        usersurname=input("User's legal surname (last)?: ")
        userdisplayname=input("Name user commonly goes by, first or first last: ")
        print("create user's access id in the following format:\n 2 character code for space agency \n 3 digits,first inital,2 digits, last inital")
        useraccessid=input("Access ID for user, AAdddIddi: ")  # 10 character string high entropy
        print("Space agency user is affiliated with, Canada,Eurpope,Japan,Russia,USA ")
        useragency=input("Space agency affiliation: ")
        # insert into DB
        nduresult=createdatauser(userforename,usersurname,userdisplayname,useraccessid,useragency)
        if nduresult is not None:
            print(dir(nduresult))
        # get the numeric user identifier
        thisuid=getuserid(useraccessid)
        if thisuid is None:
            print("error retrieving userid for account {}: ".format(useraccessid))
            answer=input("exit and investigate? (y/n):")
            if answer[:1].lower() == 'y':
                quit=True

        # prompt for password, use werkzeug.security hashing function to generate the salted password.
        print("Creating new user creds for SFR")
        pwdcheck=False
        while(not pwdcheck):
            pwd = getpass.getpass(prompt="Enter min 10 character password: ")
            shpwd=checkgenpasswd(pwd)
            if shpwd:
                newuserauthnz(pwd,shpwd,thisuid)
                pwdcheck=True 

        # End of user creation and inital authnz setup
        answer=input("continue creating users? (y/n):")
        if answer[:1].lower() == 'n':
            quit=True


if __name__ == '__main__':
    main()