-- MySQL Script generated by MySQL Workbench
-- Sun Sep  5 19:41:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ngidsv1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ngidsv1` ;

-- -----------------------------------------------------
-- Schema ngidsv1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ngidsv1` DEFAULT CHARACTER SET utf8 ;
USE `ngidsv1` ;

-- -----------------------------------------------------
-- Table `ngidsv1`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngidsv1`.`clients` ;

CREATE TABLE IF NOT EXISTS `ngidsv1`.`clients` (
  `id` INT NOT NULL,
  `email` VARCHAR(80) NULL COMMENT 'user or role email address, alerts all go to this addresses',
  `pwd` VARCHAR(120) NULL COMMENT 'assuming 60 chars will cover salt and encoding',
  `clientname` VARCHAR(80) NOT NULL COMMENT 'Optional field for putting in a company name',
  `key` VARCHAR(32) NULL COMMENT '24 char string with URL encoding\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngidsv1`.`scanjobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngidsv1`.`scanjobs` ;

CREATE TABLE IF NOT EXISTS `ngidsv1`.`scanjobs` (
  `scanid` INT NOT NULL,
  `cid` INT NOT NULL COMMENT 'foreign key in clients table',
  `scanstatus` VARCHAR(4) NOT NULL,
  `key` VARCHAR(32) NOT NULL,
  `scanstart` DATETIME NOT NULL COMMENT 'All scans need a scheduled date,  make the format for for python datetime ',
  `scanstop` DATETIME NOT NULL,
  `scantype` INT NOT NULL,
  `scantargets` VARCHAR(96) NULL COMMENT 'Making this 96 chars long, assuming that will be enough. ',
  `scansvc` VARCHAR(72) NULL COMMENT 'If we are doing something other than an arpscan we\'d need to define the service and port relationship',
  `scancreds` VARCHAR(48) NULL COMMENT 'This will be a json string, 4 chars fpr the JSON overhead, assuming we are likely 10-15 chars for username and leaves 24 chars plus for password. Should fit most applications.\n',
  `scanargs` VARCHAR(72) NULL COMMENT 'Making everything mulitples of 8, 72 should be enough for the craziest NMAP argument collection',
  PRIMARY KEY (`scanid`),
  INDEX `fk_client-id_idx` (`cid` ASC),
  CONSTRAINT `fk_client-id`
    FOREIGN KEY (`cid`)
    REFERENCES `ngidsv1`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS ngids_svc;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'ngids_svc' IDENTIFIED BY 'TH!Sb3tt3rBEg00d3';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `ngidsv1`.* TO 'ngids_svc';
SET SQL_MODE = '';
DROP USER IF EXISTS ngids_app;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'ngids_app' IDENTIFIED BY 'TH!Sisn0tReus3d';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `ngidsv1`.* TO 'ngids_app';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
