insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('03','NA_Open','North American shared research, no-GDPR restrictions',1) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('04','EU_Open','European & International shared research, potential regulatory constraints',1) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('05','EU_Commercial','Commercial users affiliated with the European space agency',1) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('06','US_Commercial','Commercial users affiliated with the US space agency',1) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('08','AP_Open','Asia Pacific & International shared research, potential regulatory constraints',1) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('09','JP_Commercial','Commercial users affiliated with the Japanese space agency',2) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('11','US_Priv','Restricted to US Space Agency members only',3) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('12','RU_Priv','Restricted to Russian Space Agency members only',3) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('14','EU_Priv','Restricted to European Space Agency members only',3) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('15','JP_Priv','Restricted to Japanese Space Agency members only',3) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('19','CA_Priv','Restricted to Canadian Space Agency members only',3) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('18','Inl_Open','International Open research, no regulatory or IP restrications',1) ;
insert into datagroups (groupid,groupname,groupdesc,grouptype) values ('60','EU_Climate','Climate data for Europe and Asia',1) ;