-- MySQL Script generated by MySQL Workbench
-- Sun Feb 20 08:37:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sfrdev
-- -----------------------------------------------------
-- Development instance  secure file repository
-- 
-- Combining access control and storage in same database to simplify replication
-- 
-- 
DROP SCHEMA IF EXISTS `sfrdev` ;

-- -----------------------------------------------------
-- Schema sfrdev
--
-- Development instance  secure file repository
-- 
-- Combining access control and storage in same database to simplify replication
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sfrdev` DEFAULT CHARACTER SET utf8 ;
USE `sfrdev` ;

-- -----------------------------------------------------
-- Table `sfrdev`.`datauser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfrdev`.`datauser` ;

CREATE TABLE IF NOT EXISTS `sfrdev`.`datauser` (
  `userid` INT NOT NULL AUTO_INCREMENT COMMENT 'auto incrementing digits,  obscured from user because they pass accessid on login page.',
  `userforename` VARCHAR(45) NOT NULL,
  `usersurname` VARCHAR(45) NOT NULL,
  `userdisplayname` VARCHAR(90) NOT NULL COMMENT 'Minimum 1 character,  max 90',
  `useraccessid` VARCHAR(12) NOT NULL COMMENT ' character agency / company code followed by up to 5 digits and 1 random letters   abcd87e497   ~ 250,000 possible usernames',
  `useragency` VARCHAR(45) NULL COMMENT 'Name of space agency user is associated with.  User can only belong to on space agency.',
  `authgroups` VARCHAR(60) NULL COMMENT 'Can contain zero to 20 2 digit numbers that represent groups the user could belong to. This provides a possible 99 unique groups.  Seperate each group identifier with a comma simplify the function retrieving membership. ',
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfrdev`.`usercredential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfrdev`.`usercredential` ;

CREATE TABLE IF NOT EXISTS `sfrdev`.`usercredential` (
  `userid` INT NOT NULL,
  `userpasswd` VARCHAR(45) NULL COMMENT 'Ensure salted hash is used',
  `userlocked` TINYINT NULL,
  `passwdchange` DATETIME NULL,
  `changepasswd` TINYINT NULL,
  PRIMARY KEY (`userid`),
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `sfrdev`.`datauser` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfrdev`.`datagroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfrdev`.`datagroups` ;

CREATE TABLE IF NOT EXISTS `sfrdev`.`datagroups` (
  `groupid` INT NOT NULL COMMENT 'two digit group number 00 - 99 gives 100 possible groups\n',
  `groupname` VARCHAR(45) NOT NULL COMMENT 'Human readable name, use underscores instead of spaces.  Naming convention TBD',
  `groupdesc` VARCHAR(90) NULL COMMENT 'Human readable description of group function and data classification',
  `grouptype` INT NOT NULL COMMENT 'Encode group function using integer values,  EG 1 = open research,  2 = commercial research, 3 = agency proprietary  etc.',
  `datauser_userid` INT NOT NULL,
  PRIMARY KEY (`groupid`),
  INDEX `fk_datagroups_datauser1_idx` (`datauser_userid` ASC),
  CONSTRAINT `fk_datagroups_datauser1`
    FOREIGN KEY (`datauser_userid`)
    REFERENCES `sfrdev`.`datauser` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS sfr_app;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'sfr_app' IDENTIFIED BY 'n0t2S#CR#T!';

GRANT ALL ON `sfrdev`.* TO 'sfr_app';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
